LedgerHQ/exchange-sdk

- .github/workflows/release.yml
- README.md
- lib/package.json
- package.json
This PR is related to this [Jira tickets](https://ledgerhq.atlassian.net/browse/LIVE-8250)
> Add versioning and release github action

- .github/workflows/release.yml
- lib/package.json
Adding some missing variable and fix some errors also.
> Update release workflow

- lib/jest.config.js
- lib/package.json
- lib/src/api.test.ts
- lib/src/api.ts
- lib/src/sdk.test.ts
- lib/src/sdk.ts
- package.json
- pnpm-lock.yaml
The features is related to [LIVE-8252](https://ledgerhq.atlassian.net/browse/LIVE-8252)
Some unit tests have been added.
[LIVE-8252]: https://ledgerhq.atlassian.net/browse/LIVE-8252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Update /swap payload and add unit tests

- example/package.json
- lib/package.json
- lib/src/sdk.ts
- pnpm-lock.yaml
Due to new WalletAPI version, the create transaction function has been update.
> Upgrade to wallet-api 1.0.2

- example/package.json
- example/src/pages/index.tsx
- lib/package.json
- lib/src/api.test.ts
- lib/src/api.ts
- lib/src/liveapp.ts
- lib/src/sdk.test.ts
- lib/src/sdk.ts
- pnpm-lock.yaml
Add rate params to support swap history
https://ledgerhq.atlassian.net/browse/LIVE-8943
> feat: add rate params

- ERROR.md
This markdown list current errors in ExchangeSDK with underlying management from Ledger Live.
> Docs with current errors

- ERROR.md
- example/src/pages/index.tsx
- lib/src/error.ts
- lib/src/index.ts
- lib/src/log.ts
- lib/src/sdk.test.ts
- lib/src/sdk.ts
Improve "errors":
Jira: https://ledgerhq.atlassian.net/browse/LIVE-9373
Doc: https://ledgerhq.atlassian.net/wiki/spaces/PTX/pages/4144530320/Errors
> fix: fix errors

- example/package.json
- example/src/pages/index.tsx
- lib/package.json
- lib/src/api.ts
- lib/src/liveapp.ts
- lib/src/sdk.ts
- pnpm-lock.yaml
Draft waiting to be updated with wallet-api new package version. (wallet-api pr https://github.com/LedgerHQ/wallet-api/pull/266)
Jira: https://ledgerhq.atlassian.net/browse/LIVE-9854
Need to update wallet-api-client version before be merged!
> fix: suppport new to token

- example/package.json
- lib/package.json
- lib/src/error.ts
- lib/src/sdk.ts
- pnpm-lock.yaml
Ref. [LIVE-10434](https://ledgerhq.atlassian.net/browse/LIVE-10434)
[LIVE-10434]: https://ledgerhq.atlassian.net/browse/LIVE-10434?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> use SWAP_NG type for startExchange

- README.md
- lib/src/api.ts
- lib/src/sdk.ts
Related to [LIVE-10920](https://ledgerhq.atlassian.net/browse/LIVE-10920)
[LIVE-10920]: https://ledgerhq.atlassian.net/browse/LIVE-10920?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Allow passing custom url for backend

- lib/src/api.test.ts
- lib/src/api.ts
[LIVE-10981]
[LIVE-10981]: https://ledgerhq.atlassian.net/browse/LIVE-10981?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> Rename swapId backend request params to rateId

- lib/src/api.ts
> fixed moonpay parsing payload

- .github/workflows/test.yml
Add Github actions for automatically run unit test on PR.
> Add test Github Action

- ERROR.md
- lib/src/handleErrors.ts
- lib/src/sdk.ts
Small update on how errors are thrown to devs for our internal tracking
> chore: update on error management

- lib/src/handleErrors.ts
Add errors to let through to LLD that are already managed there
> fix(LIVE-13100): add error to let through to LLD

- lib/src/sdk.ts
https://ledgerhq.atlassian.net/browse/LIVE-13260
> feat: handle rest of the errors

- lib/src/handleErrors.ts
https://ledgerhq.atlassian.net/browse/LIVE-13425
Add new errors to permission list
> fix(LIVE-13425): let error go to LLD that are managed

- lib/src/api.test.ts
- lib/src/api.ts
- lib/src/sdk.ts
- lib/src/wallet-api.ts
Removed wtf usage of bigint that recreated bug when converting BigNumber -> number -> bigint.
> fix: removed bigint

- lib/src/handleErrors.ts
fix double drawer for NotEnoughGas
> added a new error to not double drawer

- lib/src/sdk.test.ts
> feat: unit test

- lib/src/error.ts
- lib/src/handleErrors.ts
- lib/src/sdk.ts
> feat: Refactor sdk.ts

- lib/src/sdk.test.ts
- lib/src/sdk.ts
> feat: swap returns swap id

- lib/src/error.ts
- lib/src/handleErrors.ts
- lib/src/sdk.test.ts
- lib/src/sdk.ts
remove swap 003 creating double drawer
> fix(double-drawer): fix double drawer

- lib/src/api.test.ts
- lib/src/api.ts
- lib/src/error/ExchangeSdkError.ts
- lib/src/error/parser.ts
- lib/src/sdk.test.ts
- lib/src/sdk.ts
**WIP**
https://ledgerhq.atlassian.net/browse/LIVE-15754
> feat: add fund method

- examples/sell/src/pages/index.tsx
- examples/swap/src/pages/index.tsx
- lib/package.json
- lib/src/sdk.test.ts
- lib/src/sdk.ts
- lib/src/sdk.types.ts
- pnpm-lock.yaml
fee Strat is case sensitive on LL and requires all lower case.
This fix will prevent redefinition of the type in swap live app 
https://github.com/LedgerHQ/swap-live-app/blob/698540cd330125167bf20a99a7f5ab5397d16e39/apps/live-app/src/schemas/FeeStrategySchema.ts
> fee Strat is case sensitive and requires all lower case

- lib/package.json
- lib/src/wallet-api.ts
- pnpm-lock.yaml
Jira ticket: https://ledgerhq.atlassian.net/browse/LIVE-15797
> feat: add support for Aptos

- lib/package.json
- lib/src/error/handleErrors.ts
- pnpm-lock.yaml
- Fix issue when checking `cause.name`; it can be `undefined`
- Update peer dependencies
> fix: handleErrors method

- lib/src/api.ts
align with endpoints defined [here](https://buy.api.aws.prd.ldg-tech.com/docs/#/)
> fix: forgetransaction endpoint

- lib/src/api.ts
context: https://ledgerhq.atlassian.net/browse/LIVE-17597
> fix: swap amounts for coinify

- examples/sell/package.json
- examples/swap/package.json
- lib/package.json
- lib/src/wallet-api.ts
- pnpm-lock.yaml
> feat: add support for Sui

- lib/src/api.test.ts
- lib/src/api.ts
- lib/src/api.types.ts
- lib/src/sdk.ts
- lib/src/sdk.types.ts
Reverts LedgerHQ/exchange-sdk#118
> Revert "Feat/live 19646 ledger session"
